---

- name: Ensure s-nail
  ansible.builtin.include_role:
    name: docker_container
  vars:
    docker_container_name:           s-nail
    docker_container_image:          lwith/s-nail:latest
    docker_container_command:        tail -f /dev/null
    docker_container_restart_policy: always
    docker_container_env:
      - "SMTP_SERVER='{{ s_nail_smtp_server }}'"
      - "SMTP_PORT='{{ s_nail_smtp_port }}'"
      - "MAIL_FROM='{{ s_nail_mail_from }}'"
      - "MAIL_USER='{{ s_nail_mail_user }}'"
      - "MAIL_PASSWORD='{{ s_nail_mail_password }}'"

...